import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import commandsData from './src/data/commands.json';
import categoriesData from './src/data/categories.json';

type Command = {
  name: string;
  description: string;
  usage: string;
  example: string;
  category: string;
};
type Category = {
  id: string;
  label: string;
  description: string;
  count: number;
};

const commands = commandsData as Command[];
const categories = categoriesData as Category[];

// Commands section: flat per-command pages on disk (docs/commands/<name>.mdx,
// served at /docs/commands/<name>), but visually grouped by category in the
// sidebar via this manual construction. Lets the URLs stay flat while the
// outline matches the canonical category order from bin/noclickops.sh.
const commandsByCategory = categories
  .map((cat) => ({
    type: 'category' as const,
    label: cat.label,
    collapsible: true,
    collapsed: false,
    items: commands
      .filter((cmd) => cmd.category === cat.id)
      .map((cmd) => `commands/${cmd.name}`),
  }))
  .filter((cat) => cat.items.length > 0);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Commands',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'commands/index'},
      items: commandsByCategory,
    },
    {
      type: 'category',
      label: 'AI Developer Workflow',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'ai-developer/README'},
      items: [{type: 'autogenerated', dirName: 'ai-developer'}],
    },
  ],
};

export default sidebars;
